<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MCNJY01" ignored="0" name="testngTest" tests="5" failures="1" timestamp="21 Jun 2019 12:45:27 GMT" time="6.515" errors="0">
  <testcase name="validateAPIResponse" time="2.514" classname="com.AutomateAPI">
    <failure type="java.lang.AssertionError" message="expected [220] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [220] but found [200]
	at com.AutomateAPI.validateAPIResponse(AutomateAPI.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- validateAPIResponse -->
  <testcase name="validateGET" time="1.093" classname="com.AutomateAPI"/>
  <testcase name="doPOST" time="1.006" classname="com.AutomateAPI"/>
  <testcase name="doPUT" time="0.923" classname="com.AutomateAPI"/>
  <testcase name="doDELETE" time="0.924" classname="com.AutomateAPI"/>
</testsuite> <!-- testngTest -->
